# Your name and what you do
name: Germán Aliprandi 
bio: Un tipo más... 

description: Sitio Personal

# Profile picture
picture: assets/images/profile.jpg

# your url: https://galiprandi.github.io/me/
url: https://galiprandi.github.io/me/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: GadgetTucuman
twitter: galiprandi
linkedin: german-aliprandi-5b67b01ab
github: galiprandi
email: galiprandi@gmail.com 
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Computación 
    - Fotografía 
    - Electrónica 
    - Programación 
    - Y lo que haga falta    

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Gadget:
        name: Gadget
        description: Venta y reparación de equipos fotográficos. 
        url: https://micamara.ga
    Mialbum:
        name: miAlbum 
        description: Albumes digitales para fotógrafos. 
        url: http://mialbum.ga
    Ciudades Sostenibles:
        name: Ciudades Sostenibles
        description: Proyecto que busca consolidar la movilidad individual. 
        url: https://galiprandi.github.io/ciudades-sostenibles/
    Grupo Libélula:
        name: Grupo Libélula
        description: Espacio autogestionado promoción cultural. 
        url: https://www.facebook.com/GrupoLibelulaTuc/


# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
