name: Build Pdf

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y wkhtmltopdf
      - run: xvfb-run -- /usr/bin/wkhtmltopdf ./index.html resume.pdf
