name: Build Pdf

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./resume.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "1px", "right": "1px", "bottom": "1px"}}'

      # - name: install
      #   run: apt install wkhtmltopdf

      - name: Build PDF
        run: wkhtmltopdf index.html resume.pdf
